version: '3.9'

services:
  
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: dev_api
    environment:
      - DATABASE_PUBLIC_URL=database
    depends_on:
      - database
    restart: always
    ports:
      - "8080:80"
    
  database:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    container_name: sqlserver
    environment: 
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "seCret3pasword"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
      
  

      
#      api:
#        build:
#          context: .
#          dockerfile: ./Dockerfile
#        environment:
#          - ASPNETCORE_ENVIRONMENT=Development
#          - ASPNETCORE_URLS=http://+:80
#        links:
#          - db:db
#        ports:
#          - "8080:80"
#        volumes:
#          - ~/.aspnet/https:/root/.aspnet/https:ro
#          - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
#        depends_on:
#          - database