version: '3.8'

services: 
  
  database:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment: 
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Secret!Password0"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
      