version: '3.8'

services:
  api:
    build: 
      context: .
      dockerfile: ./Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "8080:80"
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
    depends_on:
      - database
     
  database:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment: 
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "seCret3pasword"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
  
      