version: '3.8'

services:
#  api:
#    build: .
#      context: .
#      dockerfile: ./Dockerfile
#    ports:
#      - "5000:5000"
#    depends_on:
#      - database
     
  database:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment: 
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "seCret3pasword"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
  
      